# Básico sobre matrizes

In [102]:
# multiplicação de matrizes implementada pela própria linguagem

A = rand(3,5)
B = rand(5, 4)
A * B

3×4 Array{Float64,2}:
 0.901371  1.32112  1.5118   0.52211
 1.31784   1.71442  1.74042  1.39822
 0.875512  1.29479  1.01955  1.07038

In [103]:
# algoritmo de multiplicação de matrizes

C = zeros(3, 4)

for i=1:3, j=1:4
    C[i,j] = sum(A[i,k] * B[k,j] for k=1:5)
end
C

3×4 Array{Float64,2}:
 0.901371  1.32112  1.5118   0.52211
 1.31784   1.71442  1.74042  1.39822
 0.875512  1.29479  1.01955  1.07038

In [104]:
# comparação da quantidade de memória necessária para armazenar matrizes

n = 100000

matriz_esparsa = Float64.size * (3n - 2) / 1024 / 1024 # exemplo com uma matriz laplaciana
matriz_comum = Float64.size * n^2 / 1024 / 1024

matriz_esparsa, matriz_comum # em megabytes

(2.2888031005859375, 76293.9453125)

In [105]:
# multiplicação de matriz por vetor

# essa função percorre a matriz no sentido horizontal
# ou seja, primeiro itera sobre todas as colunas para depois mudar de linha
function multAx1(A, x)
    m, n = size(A)
    y = zeros(m)
    
    for linha = 1:m
        for coluna = 1:n
            y[linha] += A[linha,coluna] * x[coluna]
        end
    end
    
    return y
end

# essa função percorre a matriz no sentido vertical
# ou seja, primeiro itera sobre todas as linhas para depois mudar de coluna
function multAx2(A, x)
    m, n = size(A)
    y = zeros(m)
    
    for coluna = 1:n
        for linha = 1:m
            y[linha] += A[linha,coluna] * x[coluna]
        end
    end
    
    return y
end

multAx2 (generic function with 2 methods)

### Testando o desempenho e eficácia de cada função

In [106]:
using BenchmarkTools # biblioteca para fazer teste de desempenho em funções

In [107]:
# Define dimensão das matrizes
n = 1000

A = rand(n, n)
x = rand(n)

y1 = multAx1(A, x)
y2 = multAx2(A, x)

# testa se esses vetores estão próximos (teste de corretude)
y1 ≈ y2 ≈ A * x

true

In [108]:
# o desempenho dessa função é pior
@benchmark multAx1($A, $x)

BenchmarkTools.Trial: 
  memory estimate:  7.94 KiB
  allocs estimate:  1
  --------------
  minimum time:     3.363 ms (0.00% GC)
  median time:      3.545 ms (0.00% GC)
  mean time:        3.635 ms (0.00% GC)
  maximum time:     7.254 ms (0.00% GC)
  --------------
  samples:          1372
  evals/sample:     1

In [109]:
# essa função desempenha bem melhor que a anterior
# imagino que seja por conta do melhor uso da memória cache
# dependendo da forma que a estrutura de dados esteja organizada no baixo nível
@benchmark multAx2($A, $x)

BenchmarkTools.Trial: 
  memory estimate:  7.94 KiB
  allocs estimate:  1
  --------------
  minimum time:     1.132 ms (0.00% GC)
  median time:      1.156 ms (0.00% GC)
  mean time:        1.218 ms (0.00% GC)
  maximum time:     3.656 ms (0.00% GC)
  --------------
  samples:          4083
  evals/sample:     1

In [110]:
using SparseArrays # biblioteca para trabalhar com matrizes esparsas

A = sprand(10, 10, 0.3) # a forma como ele printa a matriz é diferente, mostra só as posições em que há algo diferente de zero

10×10 SparseMatrixCSC{Float64,Int64} with 32 stored entries:
  [3 ,  1]  =  0.241685
  [4 ,  1]  =  0.841772
  [5 ,  1]  =  0.563358
  [8 ,  1]  =  0.672684
  [10,  1]  =  0.53812
  [5 ,  2]  =  0.873475
  [9 ,  2]  =  0.660849
  [10,  2]  =  0.758892
  [1 ,  3]  =  0.0712516
  [2 ,  3]  =  0.222792
  [5 ,  3]  =  0.843653
  [7 ,  3]  =  0.822025
  ⋮
  [4 ,  6]  =  0.102911
  [8 ,  6]  =  0.678657
  [1 ,  7]  =  0.75043
  [3 ,  7]  =  0.587887
  [5 ,  7]  =  0.770649
  [9 ,  7]  =  0.164284
  [9 ,  8]  =  0.836219
  [2 ,  9]  =  0.39427
  [3 ,  9]  =  0.41924
  [5 ,  9]  =  0.777633
  [1 , 10]  =  0.600459
  [5 , 10]  =  0.167393
  [6 , 10]  =  0.905136

In [111]:
# retorna um vetor com a posição vertical de cada elemento
# um vetor com a posição horizontal de cada elemento
# um vetor com todos os elementos não nulos da matriz

rows, cols, vals = findnz(A)

([3, 4, 5, 8, 10, 5, 9, 10, 1, 2  …  3, 5, 9, 9, 2, 3, 5, 1, 5, 6], [1, 1, 1, 1, 1, 2, 2, 2, 3, 3  …  7, 7, 7, 8, 9, 9, 9, 10, 10, 10], [0.24168493923499468, 0.8417717401755755, 0.5633579381177041, 0.6726842763010734, 0.5381195541079953, 0.8734748520665003, 0.6608487362889588, 0.75889167613772, 0.07125163795737466, 0.22279242745556793  …  0.5878872156312716, 0.7706487532278419, 0.1642836063627764, 0.8362186866390438, 0.3942699740718525, 0.41924042985798415, 0.7776331686846663, 0.600459438729912, 0.1673929788222126, 0.905136442451554])

$$$$

# Resolução de sistemas lineares

In [112]:
A = rand(3,3)
b = A * ones(3) # podemos usar isso pra já saber que o resultado é um vetor de 1

3-element Array{Float64,1}:
 0.6729498440793755
 1.362481168954216
 1.263438569202847

In [113]:
A \ b # função implementada na linguagem que resolve o sistema Ax = b

3-element Array{Float64,1}:
 1.0000000000000007
 0.9999999999999986
 1.0000000000000016

In [114]:
# eliminação gaussiana

A = [3.0 1 2; -1 2 1; 1 1 4]

m21 = A[2,1] / A[1,1] # coeficiente para zerar a primeira posição da segunda linha
m31 = A[3,1] / A[1,1] # coeficiente para zerar a primeira posição da terceira linha

A[2,:] = A[2,:] - m21 * A[1,:] # subtrai a primeira linha da segunda com um coeficiente calculado para zerar a primeira posição
A[3,:] = A[3,:] - m31 * A[1,:] # subtrai a primeira linha da terceira com um coeficiente calculado para zerar a primeira posição

m32 = A[3,2] / A[2,2] # coeficiente para zerar a segunda posição da terceira linha

A[3,:] = A[3,:] - m32 * A[2,:] # subtrai a segunda linha da terceira com um coeficiente calculado para zerar a segunda posição

A # o resultado é uma matriz triangular superior

3×3 Array{Float64,2}:
 3.0   1.0          2.0
 0.0   2.33333      1.66667
 0.0  -1.11022e-16  2.85714

In [115]:
"""
    Modifica A e b, fazendo eliminação gaussiana
"""

function eliminação_gaussiana!(A, b)
    m, n = size(A)
    
    for j = 1:n
        for i = j+1:m
            mij = A[i,j] / A[j,j] # calcula o coeficiente para zerar a posição i,j
            
            A[i,:] -= mij * A[j,:] # subtrai a linha j da linha i
            
            b[i] -= mij * b[j] # efetua a mesma operação do outro lado da equação
            
            A[i,j] = 0.0 # zera a posição i,j para evitar propagação de erros
        end
    end

    return A, b
end

eliminação_gaussiana! (generic function with 1 method)

In [116]:
A = [3.0 1 2; -1 2 1; 1 1 4]
b = A * ones(3)

eliminação_gaussiana!(A, b)

([3.0 1.0 2.0; 0.0 2.3333333333333335 1.6666666666666665; 0.0 0.0 2.857142857142857], [6.0, 4.0, 2.8571428571428568])

In [117]:
A \ b # podemos resolver o sistema e ver que a eliminação funcionou

3-element Array{Float64,1}:
 1.0
 1.0000000000000002
 0.9999999999999998

$$$$

# Gauss-Jacobi

É um método iterativo para resolver sistemas lineares de forma aproximada

Sua vantagem é que é bem mais rápido e pode ser paralelizado
Sua desvantagem é que nem sempre converge

A ideia é usar o mesmo princípio do método do ponto fixo, isolando o x da seguinte forma

$$ Ax = b \implies x = D^{-1}(b - Rx) $$

Onde $D = \begin{bmatrix}
a_{1,1} & 0 & ... & 0\\
0 & a_{1,1} & ... & 0\\
\vdots &  & \ddots & 0\\
0 & 0 & ... & a_{m,n}
\end{bmatrix}$ e $R = A - D$

In [6]:
using LinearAlgebra

In [7]:
function inverte_diagonal(D)
    m, n = size(D)
    inversa = zeros(m, n)
    
    for i = 1:m
        inversa[i,i] = 1.0 / D[i,i]
    end
    
    return inversa
end

function gauss_jacobi(A, b; tolerancia = 1e-8, max_iterações = 100, max_tempo = 10.0)
    m, n = size(A)

    D = Diagonal(A) # pega a diagonal da matriz A
    R = A - D
    D_inv = inverte_diagonal(D)

    x = rand(m) # gera um chute aleatório para ser começado
    xk = D_inv * (b - R * x)
    
    iterações = 0
    # calcula quanto tempo o programa está levando
    t0 = time()
    Δt = time() - t0
    
    # testa os critérios de parada
    resolvido() = norm(x - xk) <= tolerancia
    cansado() = (iterações >= max_iterações) || (Δt >= max_tempo)
    
    while !(resolvido() || cansado())
        x = xk
        xk = D_inv * (b - R * x)
        
        iterações += 1
        Δt = time() - t0
    end
    
    exitflag = :desconhecido
    
    # verifica qual das condições de parada foram alcançadas para retornar um feedback
    if resolvido()
        exitflag = :sucesso
    else
        if iterações >= max_iterações
            exitflag = :max_iterações
        else
            exitflag = :max_tempo
        end
    end
    
    return x, iterações, exitflag, Δt
end

gauss_jacobi (generic function with 1 method)

In [8]:
# teste com uma matriz que claramente converge pelo teorema de convergência, pois 2*A[i,i] > sum(A[i,:])
A = [15 1 1; 1 11 2; 6 2 18]
c = [6.4, 7.2, 8.9]

b = A * c # c será a resposta do algoritmo

x = gauss_jacobi(A, b, max_iterações=10000)

([6.399999998196171, 7.199999996740197, 8.899999996270218], 16, :sucesso, 0.1182258129119873)

In [9]:
# nesse caso onde A[i,i] é só um pouco maior que a soma dos outros elementos da linha
# a convergência é bem mais lenta
A = [2.1 1 1; 1 3.1 2; 6 2 8.1]
c = [6.4, 7.2, 8.9]

b = A * c

x = gauss_jacobi(A, b, max_iterações=10000)

([6.399999997135199, 7.199999997097284, 8.899999997071308], 692, :sucesso, 0.000392913818359375)

In [10]:
# nesse caso onde A[i,i] é só um muito maior que a soma dos outros elementos da linha
# a convergência é bem mais rápida
# coincidência?? imagino que não
A = [500 1 1; 1 700 2; 6 2 480]
c = [6.4, 7.2, 8.9]

b = A * c # c será a resposta do algoritmo

x = gauss_jacobi(A, b, max_iterações=10000)

([6.400000000087434, 7.200000000098931, 8.900000000224656], 5, :sucesso, 1.3828277587890625e-5)

$$$$

### Analisando o desempenho em comparação com o método da Julia

In [50]:
function matriz_que_converge(n)
    A = ones(n, n)
    A = A + (2n) * Diagonal(A) #  cria A de forma que seja sempre convergente
    
    return A
end


function testa_diferença(n)
    A = matriz_que_converge(n)
    c = ones(n)

    b = A * c # c será a resposta do algoritmo

    x, iter, flag, tempo = gauss_jacobi(A, b, max_iterações = 2000)

    t0_julia = time()
    solução_julia = A \ b
    tempo_julia = time() - t0_julia
    
    println("------ n = $n -------")
    println("As soluções são próximas? $(x ≈ c ≈ solução_julia)")
    println("Tempo Gauss-Jacobi: $(tempo)")
    println("Tempo Julia: $(tempo_julia)")
    println("Ganho com o Gauss-Jacobi: $(tempo_julia / tempo) vezes mais rápido")
    println("---------------------")
end

testa_diferença (generic function with 1 method)

In [75]:
testa_diferença(3)

------ n = 3 -------
As soluções são próximas? true
Tempo Gauss-Jacobi: 5.0067901611328125e-5
Tempo Julia: 1.811981201171875e-5
Ganho com o Gauss-Jacobi: 0.3619047619047619 vezes mais rápido
---------------------


In [76]:
testa_diferença(300)

------ n = 300 -------
As soluções são próximas? true
Tempo Gauss-Jacobi: 0.009564876556396484
Tempo Julia: 0.09540700912475586
Ganho com o Gauss-Jacobi: 9.974724562540505 vezes mais rápido
---------------------


In [79]:
testa_diferença(1000)

------ n = 1000 -------
As soluções são próximas? true
Tempo Gauss-Jacobi: 0.10318303108215332
Tempo Julia: 0.053282976150512695
Ganho com o Gauss-Jacobi: 0.5163928176144517 vezes mais rápido
---------------------


In [ ]:
"""
------ n = 10000 -------
As soluções são próximas? true
Tempo Gauss-Jacobi: 4.18436598777771
Tempo Julia: 15.223865985870361
Ganho com o Gauss-Jacobi: 3.6382730455075847 vezes mais rápido
---------------------
"""